highlighter: rouge
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://biomadeira.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /
title: Bart Kevelham's Resume
name: Bart Kevelham
email: bartkevelham@gmail.com	
email_full: mailto:bartkevelham@gmail.com
website: bart.kevelham.com
website_full: http://bart.kevelham.com
github: bkevelham
twitter: bartkevelham
city: Geneva
country: Switzerland
google_analytics: UA-4041396-6
google_maps: 'https://www.google.ch/maps/place/Geneva'

# needed for travis-ci build
exclude: [vendor]
